apiVersion: v1
kind: ConfigMap
metadata:
  name: ustbite-order-service-postgres-config
  namespace: ustbite-data
  labels:
    app: ustbite-order-service-postgres
    component: database
    service: order-service
data:
  POSTGRES_DB: ustbite_orders_db
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: ustbite-order-service-postgres
