apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ustbite-ai-agent-service-postgres-pvc
  namespace: ustbite-data
  labels:
    app: ustbite-ai-agent-service-postgres
    component: database
    service: ai-agent-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
