apiVersion: v1
kind: Service
metadata:
  name: ustbite-ai-agent-service-postgres
  namespace: ustbite-data
  labels:
    app: ustbite-ai-agent-service-postgres
    component: database
    service: ai-agent-service
spec:
  type: ClusterIP
  selector:
    app: ustbite-ai-agent-service-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
