apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kgateway
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ustbite-data
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP