apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ustbite-redis-pvc
  namespace: ustbite-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
