apiVersion: v1
kind: ConfigMap
metadata:
  name: ustbite-user-service-postgres-config
  namespace: ustbite-data
  labels:
    app: ustbite-user-service-postgres
    component: database
    service: user-service
data:
  POSTGRES_DB: ustbite_users_db
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: ustbite-user-service-postgres
