apiVersion: v1
kind: Namespace
metadata:
  name: ustbite-frontend
  labels:
    kubernetes.io/metadata.name: ustbite-frontend
    environment: production
    team: ustbite
    tier: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ustbite-backend
  labels:
    kubernetes.io/metadata.name: ustbite-backend
    environment: production
    team: ustbite
    tier: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ustbite-data
  labels:
    kubernetes.io/metadata.name: ustbite-data
    environment: production
    team: ustbite
    tier: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: ustbite-ops
  labels:
    kubernetes.io/metadata.name: ustbite-ops
    environment: production
    team: ustbite
    tier: ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    kubernetes.io/metadata.name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    kubernetes.io/metadata.name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: kgateway
  labels:
    kubernetes.io/metadata.name: kgateway
