apiVersion: v2
name: ustbite
description: Umbrella chart for the USTBite platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ustbite-user-service
    version: 0.1.0
    repository: file://../user-service
  - name: ustbite-restaurant-service
    version: 0.1.0
    repository: file://../restaurant-service
  - name: ustbite-order-service
    version: 0.1.0
    repository: file://../order-service
  - name: ustbite-payment-service
    version: 0.1.0
    repository: file://../payment-service
  - name: ustbite-delivery-service
    version: 0.1.0
    repository: file://../delivery-service
  - name: ustbite-notification-service
    version: 0.1.0
    repository: file://../notification-service
  - name: ustbite-frontend
    version: 0.1.0
    repository: file://../frontend
