apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ustbite-cart-service-postgres-pvc
  namespace: ustbite-data
  labels:
    app: ustbite-cart-service-postgres
    component: database
    service: cart-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
