apiVersion: v1
kind: ConfigMap
metadata:
  name: ustbite-delivery-service-postgres-config
  namespace: ustbite-data
  labels:
    app: ustbite-delivery-service-postgres
    component: database
    service: delivery-service
data:
  POSTGRES_DB: ustbite_delivery_db
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: ustbite-delivery-service-postgres
