
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ustbite-public-routes
  namespace: kgateway
spec:
  parentRefs:
    - name: ustbite-gateway
      namespace: kgateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ustbite-frontend-dev
          namespace: ustbite-frontend
          port: 8080
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ustbite-api-routes
  namespace: kgateway
spec:
  parentRefs:
    - name: ustbite-gateway
      namespace: kgateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/auth
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /auth
      backendRefs:
        - name: ustbite-user-service-dev
          namespace: ustbite-backend
          port: 8001

    - matches:
        - path:
            type: PathPrefix
            value: /api/users
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /users
      backendRefs:
        - name: ustbite-user-service-dev
          namespace: ustbite-backend
          port: 8001

    - matches:
        - path:
            type: PathPrefix
            value: /api/restaurants
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /restaurants
      backendRefs:
        - name: ustbite-restaurant-service-dev
          namespace: ustbite-backend
          port: 8002

    - matches:
        - path:
            type: PathPrefix
            value: /api/orders
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /orders
      backendRefs:
        - name: ustbite-order-service-dev
          namespace: ustbite-backend
          port: 8003

    - matches:
        - path:
            type: PathPrefix
            value: /api/payments
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /payments
      backendRefs:
        - name: ustbite-payment-service-dev
          namespace: ustbite-backend
          port: 8004

    - matches:
        - path:
            type: PathPrefix
            value: /api/delivery
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /delivery
      backendRefs:
        - name: ustbite-delivery-service-dev
          namespace: ustbite-backend
          port: 8005

    - matches:
        - path:
            type: PathPrefix
            value: /api/cart
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /cart
      backendRefs:
        - name: cart-service-dev
          namespace: ustbite-backend
          port: 8010

    - matches:
        - path:
            type: PathPrefix
            value: /api/agent
      timeouts:
        request: 180s
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ustbite-ai-agent-service-dev
          namespace: ustbite-backend
          port: 8009

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ustbite-argocd-route
  namespace: kgateway
spec:
  parentRefs:
    - name: ustbite-gateway
      namespace: kgateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argocd
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
