apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME }}
  SERVICE_PORT: {{ .Values.env.SERVICE_PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL }}
  DATABASE_HOST: ustbite-user-service-postgres.ustbite-app.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: ustbite_users_db
